controllers:
    resource: routing.controllers

api_login_check:
    path: /api/login_check
    methods: ['POST']

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: '/api'
        permanent: true
