api_platform:
    title: Finero API
    version: 1.0.0
    show_webby: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
        pagination_client_enabled: true
        pagination_partial: false
